language: node_js
node_js:
    - "0.10"

before_script:
    - npm install -g grunt-cli
    - npm install -g mocha
    - npm install -g istanbul
    - npm install --quiet


script:
    - grunt --trace-deprecation