module.exports = [{
    path: 'header.bbversion',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'header.requestdate',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'header.requestname',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'header.requestdob',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'request_summary.systemrequestdate',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'request_summary.filename',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'request_summary.daterange',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'request_summary.datatypes[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.first_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.middle_initial',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.last_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.suffix',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.alias',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.relationship_to_va',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.gender',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.bloodtype',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.organdonor',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.date_of_birth',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.marital_status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.current_occupation',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_address2',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_country',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_province',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.mailing_or_destination_zip/postal_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.pager_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.cell_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.fax_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.email_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.preferred_method_of_contact',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].contact_first_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].contact_last_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].relationship',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].work_phone_ext',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].cell_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].address_line_1',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].address_line_2',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].country',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].province',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].zip/post_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_demographics.emergencycontacts[0].email_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].va_treating_facility',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].first_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].middle_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].last_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].religion',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].ethnicity',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].date_of_birth',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].place_of_birth',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].age',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].gender',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].marital_status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.street_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.street_address_2',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.zip_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.county',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.country',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.cell_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].permanentaddress.email_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].eligibility.primary_eligibility_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].eligibility.service_connected_percentage',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].employment.employment_status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].employment.employer_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.insurance_company',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.effective_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.expiration_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.group_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.group_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.subscriber_id',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.subscriber_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].activeinsurance.subscriber_relationship',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.street_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.zip_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].primarynextofkin.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.street_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.zip_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].emergencycontact.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.street_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.zip_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].vaguardian.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.street_address',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.city',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.state',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.zip_code',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.home_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_demographics.facilities[0].civilguardian.work_phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.sort_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.pastappointments[0].date/time',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.pastappointments[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.pastappointments[0].status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.pastappointments[0].clinic',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_appointments.pastappointments[0].phone_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].allergy_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].date_entered',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].reaction',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].allergy_type',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].va_drug_class',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].observed/historical',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_allergies.allergies[0].comments[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].allergy_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].severity',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].diagnosed',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].reaction',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_allergies.allergies[0].comments[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].medication_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].instructions[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].refills_remaining',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].last_filled_on',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].initially_ordered_on',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].quantity',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].days_supply',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].pharmacy',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_medications.medications[0].prescription_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].medication_category',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].drug_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].prescription_number',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].strength',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].dose',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].frequency',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].start_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].stop_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].pharmacy_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].pharmacy_phone',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].reason_for_taking',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_medications.medications[0].comments',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].problem',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].date/time_entered',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].status',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].provider',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_problems.problems[0].comments[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].admission_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].admitting_physician',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].discharge_date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].discharge_physician',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_admission_discharge.admindischarge[0].summary[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.newnote',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].date_time',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].note_title',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].signed_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].co-signed_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].date/time_signed',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_notes.notes[0].raw_note[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.summary[0].immunization',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.summary[0].date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].immunization_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].date_received:',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].reaction',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].comments',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_immunizations.immunizations[0].reaction_key',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.lastkey',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].immunization_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].other',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].method',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].date_received',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].reactions',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_immunizations.immunizations[0].comments',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.newtest',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.newlab',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.lastkey',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].lab_test',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].lab_type',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].ordering_provider',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].ordering_location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].specimen',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].date/time_collected',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].collected_location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].tests[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].raw_lab[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].collection_sample',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].performing_location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_labs.labs[0].date/time_completed',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].test_name',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].location_performed',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].provider',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].results[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_labs.tests[0].comments',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.last_updated',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.summary[0].vital_sign',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.summary[0].reading',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.summary[0].date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.sorted_by',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.vitals[0].vital_sign',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.vitals[0].measurement',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.vitals[0].comments',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.vitals[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'va_vitals.vitals[0].date/time_collected',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.source',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].measurement_type',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].date',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].time',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].systolic',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].diastolic',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].comments[0]',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].heart_rate',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].body_weight',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].measure',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].body_temperature',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].method',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].pain_level',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].blood_sugar_count',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].inr_value',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].target_range',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].location',
    targetpath: '',
    targetIsArray: false
}, {
    path: 'self_vitals.vitals[0].provider',
    targetpath: '',
    targetIsArray: false
}];